#!/usr/bin/env python3
"""fix_exact_dups.py — replace exact-text duplicate options (non-answer) with real
different-concept distractors generated by deepseek. Answer index never touched."""
import json, re, urllib.request, urllib.error, time
from pathlib import Path

ROOT = Path("/data/prometric")
Q_JS = ROOT / "sdle-prep" / "data" / "questions.js"
URL = "https://api.deepseek.com/chat/completions"
KEY = "sk-ba41aeb17e7641c99cd24c4ee2e57098"

def load_bank():
    raw = open(Q_JS, encoding="utf-8").read()
    m = re.search(r"(QUESTION_BANK\s*=\s*)(\[.*\])(\s*;?)", raw, re.S)
    return json.loads(m.group(2)), m.group(1), m.group(3)

def norm(s):
    # CONSERVATIVE: case + whitespace + unicode flavor only. Never strip > < = + ; etc.
    # (">5" and "<5" are DIFFERENT answers and must not collide.)
    return str(s).lower().replace("\u2018", "'").replace("\u2019", "'") \
        .replace("\ufb02", "fl").replace("\ufb01", "fi").replace("\ufb03", "ffi").replace("\ufb04", "ffl") \
        .replace("\u00e9", "e").replace("\u00e4", "a").replace("\u00f6", "o").replace("\u00fc", "u") \
        .replace("\u00df", "ss").replace("\u03b1", "a").replace("\u03b2", "b").replace("\u03b4", "d") \
        .replace("\u2026", "...").replace("\u00b0", " deg") \
        .replace("\u201c", "\"").replace("\u201d", "\"").replace("\u2014", "-") \
        .replace("  ", " ").strip()

def call(prompt):
    body = json.dumps({"model": "deepseek-chat", "messages": [{"role": "user", "content": prompt}],
                       "temperature": 0.4, "max_tokens": 6000}).encode()
    req = urllib.request.Request(URL, body, {"Content-Type": "application/json", "Authorization": f"Bearer {KEY}"})
    try:
        resp = json.loads(urllib.request.urlopen(req, timeout=150).read())
        return resp["choices"][0]["message"]["content"]
    except Exception as e:
        return f"__{type(e).__name__}"

def main():
    bank, pre, post = load_bank()
    # find exact dup options (same normalized text as the answer, different index)
    targets = []  # (q, index)
    for q in bank:
        if q.get("usable") is False or not q.get("options"):
            continue
        opts = [str(o) for o in q["options"]]
        an = norm(opts[q["answer"]])
        for i, o in enumerate(opts):
            if i != q["answer"] and norm(o) == an:
                targets.append((q, i))
    print(f"exact dup options to replace: {len(targets)}")

    # group by question; for questions with multiple dups ask for that many distractors
    from collections import defaultdict
    groups = defaultdict(list)
    for q, i in targets:
        groups[q["id"]].append(i)
    print(f"questions affected: {len(groups)}")

    replaced = 0
    for qid, idxs in groups.items():
        q = next(x for x in bank if x["id"] == qid)
        opts = [str(o) for o in q["options"]]
        kept = [opts[i] for i in range(len(opts)) if i not in idxs and i != q["answer"]]
        ans = opts[q["answer"]]
        prompt = (
            "You are a dental board examiner. This MCQ currently has duplicate/wrong options. "
            f"Question: {q['q'][:220]}\n"
            f"Correct answer: {ans}\n"
            f"Other existing options: {kept}\n"
            f"Write {len(idxs)} SHORT wrong distractor(s) (3-9 words each) that belong to a COMPLETELY "
            "DIFFERENT dental concept/category than the correct answer and the existing options. "
            "Never rephrase or contain any existing option. "
            'Reply with ONLY a JSON array like [{"distractor":"..."}] with EXACTLY ' + str(len(idxs)) + " item(s).")
        content = call(prompt)
        if content.startswith("__") or not content:
            print(f"  {qid}: API FAILED {content[:40]}")
            continue
        try:
            dis_m = re.findall(r'"distractor"\s*:\s*"([^"]+)"', content)
            distractors = [d.strip() for d in dis_m if d.strip()]
        except Exception as e:
            print(f"  {qid}: parse fail {e}")
            continue
        if len(distractors) < len(idxs):
            print(f"  {qid}: only {len(distractors)}/{len(idxs)} distractors")
            continue
        # safety: new distractors must not collide with any option
        allnorm = {norm(o) for o in opts}
        bad = [d for d in distractors[:len(idxs)] if not d or norm(d) in allnorm or len(d) > 60]
        if bad:
            print(f"  {qid}: rejected colliding {bad}")
            continue
        for idx, d in zip(idxs, distractors[:len(idxs)]):
            q["options"][idx] = d
            replaced += 1
        print(f"  {qid}: replaced {len(idxs)} options -> {distractors[:len(idxs)]}")
        time.sleep(0.5)

    with open(Q_JS, "w", encoding="utf-8") as f:
        f.write(pre + json.dumps(bank, ensure_ascii=False) + post)
    print(f"DONE — replaced {replaced} duplicate options")

if __name__ == "__main__":
    main()
